// Country centroid data for geocoding free-text GitHub locations.
//
// Each entry has a canonical country name and an approximate centroid
// {lat, lng}. Centroids are representative interior points (roughly the
// population/geographic center), good enough to drop a globe marker on
// the right country. They are NOT survey-grade.
//
// COUNTRY_ALIASES maps lowercased free-text spellings, abbreviations and
// native-language names to a canonical country name. Resolution flow used
// by geocode.ts: normalize token -> COUNTRY_ALIASES[token] (if present) ->
// COUNTRY_CENTROIDS[canonical].

export interface Centroid {
	lat: number;
	lng: number;
}

// Canonical country name -> centroid. >=120 countries.
export const COUNTRY_CENTROIDS: Record<string, Centroid> = {
	Afghanistan: { lat: 33.94, lng: 67.71 },
	Albania: { lat: 41.15, lng: 20.17 },
	Algeria: { lat: 28.03, lng: 1.66 },
	Angola: { lat: -11.2, lng: 17.87 },
	Argentina: { lat: -38.42, lng: -63.62 },
	Armenia: { lat: 40.07, lng: 45.04 },
	Australia: { lat: -25.27, lng: 133.78 },
	Austria: { lat: 47.52, lng: 14.55 },
	Azerbaijan: { lat: 40.14, lng: 47.58 },
	Bahamas: { lat: 25.03, lng: -77.4 },
	Bahrain: { lat: 26.07, lng: 50.56 },
	Bangladesh: { lat: 23.68, lng: 90.36 },
	Barbados: { lat: 13.19, lng: -59.54 },
	Belarus: { lat: 53.71, lng: 27.95 },
	Belgium: { lat: 50.5, lng: 4.47 },
	Belize: { lat: 17.19, lng: -88.5 },
	Benin: { lat: 9.31, lng: 2.32 },
	Bolivia: { lat: -16.29, lng: -63.59 },
	'Bosnia and Herzegovina': { lat: 43.92, lng: 17.68 },
	Botswana: { lat: -22.33, lng: 24.68 },
	Brazil: { lat: -14.24, lng: -51.93 },
	Brunei: { lat: 4.54, lng: 114.73 },
	Bulgaria: { lat: 42.73, lng: 25.49 },
	'Burkina Faso': { lat: 12.24, lng: -1.56 },
	Cambodia: { lat: 12.57, lng: 104.99 },
	Cameroon: { lat: 7.37, lng: 12.35 },
	Canada: { lat: 56.13, lng: -106.35 },
	Chile: { lat: -35.68, lng: -71.54 },
	China: { lat: 35.86, lng: 104.2 },
	Colombia: { lat: 4.57, lng: -74.3 },
	'Costa Rica': { lat: 9.75, lng: -83.75 },
	Croatia: { lat: 45.1, lng: 15.2 },
	Cuba: { lat: 21.52, lng: -77.78 },
	Cyprus: { lat: 35.13, lng: 33.43 },
	Czechia: { lat: 49.82, lng: 15.47 },
	Denmark: { lat: 56.26, lng: 9.5 },
	'Dominican Republic': { lat: 18.74, lng: -70.16 },
	Ecuador: { lat: -1.83, lng: -78.18 },
	Egypt: { lat: 26.82, lng: 30.8 },
	'El Salvador': { lat: 13.79, lng: -88.9 },
	Estonia: { lat: 58.6, lng: 25.01 },
	Ethiopia: { lat: 9.15, lng: 40.49 },
	Fiji: { lat: -17.71, lng: 178.07 },
	Finland: { lat: 61.92, lng: 25.75 },
	France: { lat: 46.6, lng: 2.21 },
	Georgia: { lat: 42.32, lng: 43.36 },
	Germany: { lat: 51.17, lng: 10.45 },
	Ghana: { lat: 7.95, lng: -1.02 },
	Greece: { lat: 39.07, lng: 21.82 },
	Guatemala: { lat: 15.78, lng: -90.23 },
	Honduras: { lat: 15.2, lng: -86.24 },
	'Hong Kong': { lat: 22.32, lng: 114.17 },
	Hungary: { lat: 47.16, lng: 19.5 },
	Iceland: { lat: 64.96, lng: -19.02 },
	India: { lat: 20.59, lng: 78.96 },
	Indonesia: { lat: -0.79, lng: 113.92 },
	Iran: { lat: 32.43, lng: 53.69 },
	Iraq: { lat: 33.22, lng: 43.68 },
	Ireland: { lat: 53.41, lng: -8.24 },
	Israel: { lat: 31.05, lng: 34.85 },
	Italy: { lat: 41.87, lng: 12.57 },
	'Ivory Coast': { lat: 7.54, lng: -5.55 },
	Jamaica: { lat: 18.11, lng: -77.3 },
	Japan: { lat: 36.2, lng: 138.25 },
	Jordan: { lat: 30.59, lng: 36.24 },
	Kazakhstan: { lat: 48.02, lng: 66.92 },
	Kenya: { lat: -0.02, lng: 37.91 },
	Kuwait: { lat: 29.31, lng: 47.48 },
	Kyrgyzstan: { lat: 41.2, lng: 74.77 },
	Laos: { lat: 19.86, lng: 102.5 },
	Latvia: { lat: 56.88, lng: 24.6 },
	Lebanon: { lat: 33.85, lng: 35.86 },
	Libya: { lat: 26.34, lng: 17.23 },
	Lithuania: { lat: 55.17, lng: 23.88 },
	Luxembourg: { lat: 49.82, lng: 6.13 },
	Macau: { lat: 22.2, lng: 113.54 },
	Madagascar: { lat: -18.77, lng: 46.87 },
	Malawi: { lat: -13.25, lng: 34.3 },
	Malaysia: { lat: 4.21, lng: 101.98 },
	Maldives: { lat: 3.2, lng: 73.22 },
	Mali: { lat: 17.57, lng: -3.996 },
	Malta: { lat: 35.94, lng: 14.38 },
	Mauritius: { lat: -20.35, lng: 57.55 },
	Mexico: { lat: 23.63, lng: -102.55 },
	Moldova: { lat: 47.41, lng: 28.37 },
	Monaco: { lat: 43.74, lng: 7.42 },
	Mongolia: { lat: 46.86, lng: 103.85 },
	Montenegro: { lat: 42.71, lng: 19.37 },
	Morocco: { lat: 31.79, lng: -7.09 },
	Mozambique: { lat: -18.67, lng: 35.53 },
	Myanmar: { lat: 21.91, lng: 95.96 },
	Namibia: { lat: -22.96, lng: 18.49 },
	Nepal: { lat: 28.39, lng: 84.12 },
	Netherlands: { lat: 52.13, lng: 5.29 },
	'New Zealand': { lat: -40.9, lng: 174.89 },
	Nicaragua: { lat: 12.87, lng: -85.21 },
	Nigeria: { lat: 9.08, lng: 8.68 },
	'North Macedonia': { lat: 41.61, lng: 21.75 },
	Norway: { lat: 60.47, lng: 8.47 },
	Oman: { lat: 21.51, lng: 55.92 },
	Pakistan: { lat: 30.38, lng: 69.35 },
	Palestine: { lat: 31.95, lng: 35.23 },
	Panama: { lat: 8.54, lng: -80.78 },
	'Papua New Guinea': { lat: -6.31, lng: 143.96 },
	Paraguay: { lat: -23.44, lng: -58.44 },
	Peru: { lat: -9.19, lng: -75.02 },
	Philippines: { lat: 12.88, lng: 121.77 },
	Poland: { lat: 51.92, lng: 19.15 },
	Portugal: { lat: 39.4, lng: -8.22 },
	Qatar: { lat: 25.35, lng: 51.18 },
	Romania: { lat: 45.94, lng: 24.97 },
	Russia: { lat: 61.52, lng: 105.32 },
	Rwanda: { lat: -1.94, lng: 29.87 },
	'Saudi Arabia': { lat: 23.89, lng: 45.08 },
	Senegal: { lat: 14.5, lng: -14.45 },
	Serbia: { lat: 44.02, lng: 21.01 },
	Singapore: { lat: 1.35, lng: 103.82 },
	Slovakia: { lat: 48.67, lng: 19.7 },
	Slovenia: { lat: 46.15, lng: 14.99 },
	'South Africa': { lat: -30.56, lng: 22.94 },
	'South Korea': { lat: 35.91, lng: 127.77 },
	Spain: { lat: 40.46, lng: -3.75 },
	'Sri Lanka': { lat: 7.87, lng: 80.77 },
	Sudan: { lat: 12.86, lng: 30.22 },
	Sweden: { lat: 60.13, lng: 18.64 },
	Switzerland: { lat: 46.82, lng: 8.23 },
	Syria: { lat: 34.8, lng: 38.997 },
	Taiwan: { lat: 23.7, lng: 120.96 },
	Tajikistan: { lat: 38.86, lng: 71.28 },
	Tanzania: { lat: -6.37, lng: 34.89 },
	Thailand: { lat: 15.87, lng: 100.99 },
	Tunisia: { lat: 33.89, lng: 9.54 },
	Turkey: { lat: 38.96, lng: 35.24 },
	Turkmenistan: { lat: 38.97, lng: 59.56 },
	Uganda: { lat: 1.37, lng: 32.29 },
	Ukraine: { lat: 48.38, lng: 31.17 },
	'United Arab Emirates': { lat: 23.42, lng: 53.85 },
	'United Kingdom': { lat: 55.38, lng: -3.44 },
	'United States': { lat: 39.83, lng: -98.58 },
	Uruguay: { lat: -32.52, lng: -55.77 },
	Uzbekistan: { lat: 41.38, lng: 64.59 },
	Venezuela: { lat: 6.42, lng: -66.59 },
	Vietnam: { lat: 14.06, lng: 108.28 },
	Yemen: { lat: 15.55, lng: 48.52 },
	Zambia: { lat: -13.13, lng: 27.85 },
	Zimbabwe: { lat: -19.02, lng: 29.15 }
};

// Lowercased free-text spelling / abbreviation / native name -> canonical
// country name (a key of COUNTRY_CENTROIDS). Keep all keys lowercase; the
// geocoder lowercases input before lookup.
export const COUNTRY_ALIASES: Record<string, string> = {
	// United States
	usa: 'United States',
	us: 'United States',
	'u.s.': 'United States',
	'u.s.a.': 'United States',
	'u.s.a': 'United States',
	america: 'United States',
	'the states': 'United States',
	'united states': 'United States',
	'united states of america': 'United States',
	// United Kingdom
	uk: 'United Kingdom',
	'u.k.': 'United Kingdom',
	'united kingdom': 'United Kingdom',
	'great britain': 'United Kingdom',
	britain: 'United Kingdom',
	gb: 'United Kingdom',
	england: 'United Kingdom',
	scotland: 'United Kingdom',
	wales: 'United Kingdom',
	'northern ireland': 'United Kingdom',
	// United Arab Emirates
	uae: 'United Arab Emirates',
	'u.a.e.': 'United Arab Emirates',
	emirates: 'United Arab Emirates',
	'united arab emirates': 'United Arab Emirates',
	// Germany
	germany: 'Germany',
	deutschland: 'Germany',
	ger: 'Germany',
	de: 'Germany',
	// Brazil
	brazil: 'Brazil',
	brasil: 'Brazil',
	br: 'Brazil',
	// Russia
	russia: 'Russia',
	'russian federation': 'Russia',
	россия: 'Russia',
	росси́я: 'Russia',
	rus: 'Russia',
	// Netherlands
	netherlands: 'Netherlands',
	holland: 'Netherlands',
	'the netherlands': 'Netherlands',
	nederland: 'Netherlands',
	nl: 'Netherlands',
	// Spain
	spain: 'Spain',
	españa: 'Spain',
	espana: 'Spain',
	es: 'Spain',
	// Italy
	italy: 'Italy',
	italia: 'Italy',
	it: 'Italy',
	// France
	france: 'France',
	fr: 'France',
	// China
	china: 'China',
	prc: 'China',
	中国: 'China',
	"people's republic of china": 'China',
	cn: 'China',
	// Japan
	japan: 'Japan',
	日本: 'Japan',
	nippon: 'Japan',
	jp: 'Japan',
	// South Korea
	'south korea': 'South Korea',
	korea: 'South Korea',
	'republic of korea': 'South Korea',
	대한민국: 'South Korea',
	한국: 'South Korea',
	rok: 'South Korea',
	kr: 'South Korea',
	// India
	india: 'India',
	भारत: 'India',
	bharat: 'India',
	in: 'India',
	// Czechia
	czechia: 'Czechia',
	'czech republic': 'Czechia',
	cesko: 'Czechia',
	česko: 'Czechia',
	// Turkey
	turkey: 'Turkey',
	türkiye: 'Turkey',
	turkiye: 'Turkey',
	// Ivory Coast
	'ivory coast': 'Ivory Coast',
	"côte d'ivoire": 'Ivory Coast',
	"cote d'ivoire": 'Ivory Coast',
	// Other common short forms / spellings
	'south africa': 'South Africa',
	rsa: 'South Africa',
	'new zealand': 'New Zealand',
	nz: 'New Zealand',
	'hong kong': 'Hong Kong',
	hk: 'Hong Kong',
	'saudi arabia': 'Saudi Arabia',
	ksa: 'Saudi Arabia',
	'el salvador': 'El Salvador',
	'costa rica': 'Costa Rica',
	'dominican republic': 'Dominican Republic',
	'bosnia and herzegovina': 'Bosnia and Herzegovina',
	bosnia: 'Bosnia and Herzegovina',
	'north macedonia': 'North Macedonia',
	macedonia: 'North Macedonia',
	'sri lanka': 'Sri Lanka',
	'united arab': 'United Arab Emirates',
	'papua new guinea': 'Papua New Guinea',
	'burkina faso': 'Burkina Faso',
	bangladesh: 'Bangladesh',
	bd: 'Bangladesh',
	philippines: 'Philippines',
	ph: 'Philippines',
	pinas: 'Philippines',
	pilipinas: 'Philippines',
	indonesia: 'Indonesia',
	id: 'Indonesia',
	vietnam: 'Vietnam',
	'viet nam': 'Vietnam',
	vn: 'Vietnam',
	canada: 'Canada',
	ca: 'Canada',
	australia: 'Australia',
	aus: 'Australia',
	au: 'Australia',
	mexico: 'Mexico',
	méxico: 'Mexico',
	mx: 'Mexico',
	argentina: 'Argentina',
	ar: 'Argentina',
	poland: 'Poland',
	polska: 'Poland',
	pl: 'Poland',
	ukraine: 'Ukraine',
	україна: 'Ukraine',
	ua: 'Ukraine',
	sweden: 'Sweden',
	sverige: 'Sweden',
	se: 'Sweden',
	norway: 'Norway',
	norge: 'Norway',
	no: 'Norway',
	finland: 'Finland',
	suomi: 'Finland',
	fi: 'Finland',
	denmark: 'Denmark',
	danmark: 'Denmark',
	dk: 'Denmark',
	switzerland: 'Switzerland',
	schweiz: 'Switzerland',
	suisse: 'Switzerland',
	ch: 'Switzerland',
	austria: 'Austria',
	österreich: 'Austria',
	at: 'Austria',
	belgium: 'Belgium',
	belgië: 'Belgium',
	belgique: 'Belgium',
	be: 'Belgium',
	portugal: 'Portugal',
	pt: 'Portugal',
	greece: 'Greece',
	ελλάδα: 'Greece',
	gr: 'Greece',
	ireland: 'Ireland',
	eire: 'Ireland',
	éire: 'Ireland',
	ie: 'Ireland',
	israel: 'Israel',
	il: 'Israel',
	singapore: 'Singapore',
	sg: 'Singapore',
	malaysia: 'Malaysia',
	my: 'Malaysia',
	thailand: 'Thailand',
	th: 'Thailand',
	pakistan: 'Pakistan',
	pk: 'Pakistan',
	nigeria: 'Nigeria',
	ng: 'Nigeria',
	kenya: 'Kenya',
	ke: 'Kenya',
	egypt: 'Egypt',
	eg: 'Egypt',
	iran: 'Iran',
	persia: 'Iran',
	ir: 'Iran',
	colombia: 'Colombia',
	co: 'Colombia',
	chile: 'Chile',
	cl: 'Chile',
	peru: 'Peru',
	perú: 'Peru',
	pe: 'Peru',
	romania: 'Romania',
	românia: 'Romania',
	ro: 'Romania',
	hungary: 'Hungary',
	magyarorszag: 'Hungary',
	magyarország: 'Hungary',
	hu: 'Hungary',
	taiwan: 'Taiwan',
	台灣: 'Taiwan',
	tw: 'Taiwan',
	estonia: 'Estonia',
	eesti: 'Estonia',
	ee: 'Estonia',
	lithuania: 'Lithuania',
	lietuva: 'Lithuania',
	lt: 'Lithuania',
	latvia: 'Latvia',
	latvija: 'Latvia',
	lv: 'Latvia',
	croatia: 'Croatia',
	hrvatska: 'Croatia',
	hr: 'Croatia',
	serbia: 'Serbia',
	srbija: 'Serbia',
	rs: 'Serbia',
	bulgaria: 'Bulgaria',
	bg: 'Bulgaria',
	slovakia: 'Slovakia',
	slovensko: 'Slovakia',
	sk: 'Slovakia',
	slovenia: 'Slovenia',
	slovenija: 'Slovenia',
	si: 'Slovenia'
};
